import { Archivo } from 'next/font/google';
import './globals.css';
import Footer from '../components/Footer';
import DomainContextProvider from '@/context/DomainContext';

const archivo = Archivo({ subsets: ['latin'] });

export const metadata = {
  title: 'Cloudnetvox',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={archivo.className}>
        <DomainContextProvider>
          {children}
          <Footer />
        </DomainContextProvider>
      </body>
    </html>
  );
}
